### ISSUE TITLE
Error updating the package

### ISSUE THREAD

**Issue by nikosGeography** [imbs-hl/ranger#676] opened 2023-06-25 13:38 UTC
On Windows 11 laptop I tried to update terra to it's latest varsion (v 0.15.1) but I am getting this error:
```
make: *** [C:/PROGRA~1/R/R-41~1.1/etc/i386/Makeconf:245: Forest.o] Error 1
ERROR: compilation failed for package 'ranger'
* removing 'C:/Program Files/R/R-4.1.1/library/ranger'
* restoring previous 'C:/Program Files/R/R-4.1.1/library/ranger'
Warning in install.packages :
  installation of package ‘ranger’ had non-zero exit status
```
I tried updating the package through RStudio.
Currently, I am having the v 0.14.1 installed. I am using RStudio Version 1.4.1717 and R v 4.1.1. Any ideas why this error?

**Comment by stephematician** [comment] 2023-06-25 23:48
Can you provide output of `sessionInfo()` and `Sys.which('make')`?

**Comment by nikosGeography** [comment] 2023-06-26 08:08
Sure. The `sessionInfo()`'s output is:
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.1.1   magrittr_2.0.3   cli_3.6.1        tools_4.1.1     
 [5] fs_1.6.2         rstudioapi_0.14  Rcpp_1.0.10      vctrs_0.6.3     
 [9] codetools_0.2-19 lifecycle_1.0.3  rlang_1.1.1      purrr_1.0.1     
[13] terra_1.7-29 
```

The `Sys.which('make')`'s:
```
make 
  ""
```

**Comment by stephematician** [comment] 2023-06-26 08:34
Looks like the problem is that [RTools](https://cran.r-project.org/bin/windows/Rtools/) (4.0) is either not installed, or the paths haven't been set correctly. I'm basing this on the output `ERROR: compilation failed for package 'ranger'` which indicates that R is attempting to compile the program, but not having any luck. `Sys.which('make')` or `Sys.which('gcc')` should result in something like:

```
Sys.which('gcc')
C:\<your rtools path>\x86_64-w64-mingw32.static.posix\bin\gcc.exe
```

Have you been through the instructions here: <https://cran.r-project.org/bin/windows/Rtools/rtools40.html> ?

**Comment by nikosGeography** [comment] 2023-06-26 09:18
Yes, I installed RTools (4.0) based on the link you provided. And I've been using other packages that require RTools (for example, based on the link for RTools, I can install the jsonlite package without an issue). Should I make a fresh install of RTools?

**Comment by stephematician** [comment] 2023-06-26 09:54
Well that's hopefully one issue fixed. You should look for more detail about the error. It might also be a good idea to start with `x86_64` build which is your system 'default' - rather than `i386`. To do both try:

```r
install.packages('ranger', type='source', INSTALL_opts='--no-multiarch', verbose=TRUE)
```

If you can get that working, then you can check if `i386` is building by removing the `INSTALL_opts` argument (if you care about having both installed). If you get stuck, feel free to put further details on here and we'll see if we can figure out a next step. I can't think of any reason why it wouldn't build - I was able to build it not too long ago myself.

**Comment by stephematician** [comment] 2023-06-26 12:06
It still looks like RTools hasn't installed or been set up successfully.

Check again that the path is set correctly via:

```r
Sys.getenv('PATH')
Sys.getenv('RTOOLS40_HOME')
```

You should also check that `gcc.exe` is an actual file contained in `C:\RTOOLS42_HOME/usr/bin` (replace RTOOLS40_HOME with the appropriate folder that RTools 4.0 was installed to).

Also, double check that the error you are getting is truly identical: I don't think it should be trying to install `i386` when using the `--no-multiarch` flag (which the msg above implies).

Until `Sys.which('gcc')` gives meaningful output, it should not be possible to compile packages from source.

**Comment by nikosGeography** [comment] 2023-06-26 12:20
Right. So the `Sys.getenv('PATH')` gives:
`[1] "C:\\rtools40\\usr\\bin;C:\\Program Files\\R\\R-4.1.1\\bin\\x64;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\GDAL;C:\\Program Files\\Calibre2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Users\\Geography\\Documents\\CMake\\bin;C:\\CMake\\bin;C:\\Users\\Geography\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\Geography\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\Geography\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\\Users\\Geography\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Users\\Geography\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Geography\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Users\\Geography\\AppData\\Roaming\\TinyTeX\\bin\\win32;C:\\Users\\Geography\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Users\\Geography\\.dotnet\\tools;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.2.3\\bin"`
The `Sys.getenv('RTOOLS40_HOME')` shows:
`"C:\\rtools40"`
And there is **no** actual `gcc.exe` file under `C:\rtools40\usr\bin`.

As for the installation using the `multiarch` option, when I type `install.packages('ranger', type='source', INSTALL_opts='--no-multiarch', verbose=TRUE)` I'm getting the following error:
```
Forest.cpp:850:19: error: 'make_unique' is not a member of 'std'
     result = std::make_unique<DataDouble>();
                   ^~~~~~~~~~~
Forest.cpp:850:19: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
Forest.cpp:26:1:
+#include <memory>
 
Forest.cpp:850:19:
     result = std::make_unique<DataDouble>();
                   ^~~~~~~~~~~
Forest.cpp:850:41: error: expected primary-expression before '>' token
     result = std::make_unique<DataDouble>();
                                         ^
Forest.cpp:850:43: error: expected primary-expression before ')' token
     result = std::make_unique<DataDouble>();
                                           ^
Forest.cpp:853:19: error: 'make_unique' is not a member of 'std'
     result = std::make_unique<DataFloat>();
                   ^~~~~~~~~~~
Forest.cpp:853:19: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
Forest.cpp:853:40: error: expected primary-expression before '>' token
     result = std::make_unique<DataFloat>();
                                        ^
Forest.cpp:853:42: error: expected primary-expression before ')' token
     result = std::make_unique<DataFloat>();
                                          ^
Forest.cpp:856:19: error: 'make_unique' is not a member of 'std'
     result = std::make_unique<DataChar>();
                   ^~~~~~~~~~~
Forest.cpp:856:19: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
Forest.cpp:856:39: error: expected primary-expression before '>' token
     result = std::make_unique<DataChar>();
                                       ^
Forest.cpp:856:41: error: expected primary-expression before ')' token
     result = std::make_unique<DataChar>();
                                         ^
make: *** [C:/PROGRA~1/R/R-41~1.1/etc/x64/Makeconf:245: Forest.o] Error 1
ERROR: compilation failed for package 'ranger'
* removing 'C:/Program Files/R/R-4.1.1/library/ranger'
* restoring previous 'C:/Program Files/R/R-4.1.1/library/ranger'
Warning in install.packages :
  installation of package ‘ranger’ had non-zero exit status
```
When I type `install.packages('ranger', type='source', verbose=TRUE)`:
```
Forest.cpp:850:19: error: 'make_unique' is not a member of 'std'
     result = std::make_unique<DataDouble>();
                   ^~~~~~~~~~~
Forest.cpp:850:19: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
Forest.cpp:26:1:
+#include <memory>
 
Forest.cpp:850:19:
     result = std::make_unique<DataDouble>();
                   ^~~~~~~~~~~
Forest.cpp:850:41: error: expected primary-expression before '>' token
     result = std::make_unique<DataDouble>();
                                         ^
Forest.cpp:850:43: error: expected primary-expression before ')' token
     result = std::make_unique<DataDouble>();
                                           ^
Forest.cpp:853:19: error: 'make_unique' is not a member of 'std'
     result = std::make_unique<DataFloat>();
                   ^~~~~~~~~~~
Forest.cpp:853:19: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
Forest.cpp:853:40: error: expected primary-expression before '>' token
     result = std::make_unique<DataFloat>();
                                        ^
Forest.cpp:853:42: error: expected primary-expression before ')' token
     result = std::make_unique<DataFloat>();
                                          ^
Forest.cpp:856:19: error: 'make_unique' is not a member of 'std'
     result = std::make_unique<DataChar>();
                   ^~~~~~~~~~~
Forest.cpp:856:19: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
Forest.cpp:856:39: error: expected primary-expression before '>' token
     result = std::make_unique<DataChar>();
                                       ^
Forest.cpp:856:41: error: expected primary-expression before ')' token
     result = std::make_unique<DataChar>();
                                         ^
make: *** [C:/PROGRA~1/R/R-41~1.1/etc/i386/Makeconf:245: Forest.o] Error 1
ERROR: compilation failed for package 'ranger'
* removing 'C:/Program Files/R/R-4.1.1/library/ranger'
* restoring previous 'C:/Program Files/R/R-4.1.1/library/ranger'
Warning in install.packages :
  installation of package ‘ranger’ had non-zero exit status
```

**Comment by stephematician** [comment] 2023-06-26 12:29
I can't see what compiler your system is trying to use - for example - because the full output (including the commands) isn't included above. If possible - attach anything that's output to the console after you invoke `install.packages` as a text file.

**Comment by nikosGeography** [comment] 2023-06-26 12:39
[error.txt](https://github.com/imbs-hl/ranger/files/11868961/error.txt)

**Comment by stephematician** [comment] 2023-06-26 13:09
Ah, this is a duplicate of #669.

I think one possible fix is to add `PKG_CXXFLAGS=-std=gnu++14` (or it might be `CXXFLAGS` - I don't have a machine on me to test right now) to a new file `~/.R/Makevars.win` provided you don't have another makevars-like file that overrides it e.g. a site-wide Makevars (you can check if you do via `tools::makevars_site()`). You can also check that the new user-makevars has been loaded via `tools::makevars_user()`.

Hope that helps you on your way. See also the discussion in the other issue.

Also if you need to know the absolute path for `~/` is use:

```r
normalizePath('~/')
```

And if you do create a `~/.R/Makevars.win` you'll need to restart R. Also this _may_ interfere with other packages so you might need to remove this file after ranger has installed.

Aaaaand - this is all because of a faulty setting introduced in R 4.0.x-4.1.x or so. If you update R to the latest version this has been resolved.

**Comment by nikosGeography** [comment] 2023-06-26 13:21
Thank you, I will check it. And I just checked the path to gcc.exe. In my case, the `gcc.exe` is located here `C:\rtools40\mingw64\bin` (I just found out).

**Comment by stephematician** [comment] 2023-06-26 13:27
Sorry I think it might be "CPP" not "CXX" in the names of the variables I mentioned above.

**Comment by nikosGeography** [comment] 2023-06-26 20:48
So I think I managed to solve the issue. I deleted R, RStudio and RTools from my machine and I made a fresh install (R-3.4.1, RStudio 1.4.1743 and RTools 4.2). Then, I created a .Renviron file in the Documents folder where I typed the following:
`PATH="${RTOOLS42_HOME}\usr\bin;${PATH};${RTOOLS42_HOME}\x86_64-w64-mingw32.static.posix\bin"`.

Now when I type Sys.which("make") I get:
`"C:\\rtools42\\usr\\bin\\make.exe"`
and Sys.which("gcc"):
`"C:\\rtools42\\X86_64~1.POS\\bin\\gcc.exe"`.
After setting the paths correctly I installed the latest version of the package `ranger `successfully on my laptop.

**Closed** 2023-06-27 08:49 UTC
