### ISSUE TITLE
How to correctly work with unordered factors in ranger

### ISSUE THREAD

**Issue by tchakravarty** [imbs-hl/ranger#36] opened 2016-02-04 17:01 UTC
I am trying to understand how I should enter unordered factors in `ranger`: 

``` R
# create some sample data
df_foo = data_frame(
  factor1 = factor(sample(LETTERS[1:10], size = 1000, replace = TRUE)),
  numeric1 = rnorm(1000),
  target = as.factor(sample(c(0, 1), size = 1000, replace = TRUE))
)

# respect.unordered.factors = TRUE 
# factor
ranger_foo_1 = ranger(
  formula = target ~ factor1 + numeric1,
  data = df_foo,
  num.trees = 100, 
  mtry = 2, 
  min.node.size = 10,
  respect.unordered.factors = TRUE,
  seed = 1234
)

# respect.unordered.factors = TRUE 
# character
ranger_foo_2 = ranger(
  formula = target ~ as.character(factor1) + numeric1,
  data = df_foo,
  num.trees = 100, 
  mtry = 2, 
  min.node.size = 10,
  respect.unordered.factors = TRUE,
  seed = 1234
)

# respect.unordered.factors = FALSE 
# character
ranger_foo_3 = ranger(
  formula = target ~ as.character(factor1) + numeric1,
  data = df_foo,
  num.trees = 100, 
  mtry = 2, 
  min.node.size = 10,
  respect.unordered.factors = FALSE,
  seed = 1234
)

# respect.unordered.factors = FALSE
# factor
ranger_foo_4 = ranger(
  formula = target ~ factor1 + numeric1,
  data = df_foo,
  num.trees = 100, 
  mtry = 2, 
  min.node.size = 10,
  respect.unordered.factors = FALSE,
  seed = 1234, 

)

# check the differences among the results
ranger_foo_1
ranger_foo_2
ranger_foo_3
ranger_foo_4
```

The result of `ranger_foo_1` is different from the rest. Assuming that from a theoretical point of view, this is the right answer (basically equivalent to one-hot encoding of the variables), should I always explicitly convert my character variables into factor before entering them into `ranger`?  What then does the call with `respect.unordered.factors = TRUE` and `as.character(factor1)` (`ranger_foo_2`) do, in terms of computation?

Thanks.

**Comment by mnwright** [comment] 2016-02-04 17:39
In the current implementation you have to code the characters as factors to consider them unordered (Internally we check for is.factor & !is.ordered). In foo2 the characters are converted to ordered factors and there should be no computational differences to foo3 and foo4. 

You are right to be confused, characters should be considered as unordered if respect.unordered.factors = TRUE (as in foo2). 

Any objections?

**Comment by tchakravarty** [comment] 2016-02-04 17:44
Absolutely not, and thanks for the quick reply. I would say that in case I have a character feature and I have set `respect.unordered.factors=TRUE`, I would expect the coercion to factor to be unordered as well. Actually, I am just going through your [excellent vignette ](http://arxiv.org/abs/1508.04409), and as long as it is documented, it shouldn't matter.

**Comment by tchakravarty** [comment] 2016-02-07 14:34
@mnwright Adding some further information to this discussion -- let me know if this requires an issue of its own. To summarize the discussion so far, a resolution to this issue will involve changing the handling of coercion of character variables to factor (currently coreced to ordered factor) when `respect.unordered.factors=TRUE` is set. 

However, I have run into a deeper issue. When I do have a some unordered factor variables in the data (they are declared as such), and pass them to ranger, ranger hangs and does not appear to be doing anything. 

Here is a reproducible example: 

```{R}
library(wakefield)
library(ranger)

# using wakefield
sample_size = 1e6
df_foo = r_data_frame(
  n = sample_size,
  ID = id,
  y = dummy,
  r_series(wakefield::r_sample_factor, j = 10, n = sample_size, name = "Factor")
)

# create the formula object
formula_ranger = as.formula(paste0("y ~", paste0("Factor_", 1:10, collapse = "+")))

# run ranger
ranger_foo = ranger(formula = formula_ranger, 
       data = df_foo, 
       num.trees = 100, 
       mtry = 4,
       write.forest = TRUE, 
       respect.unordered.factors = TRUE)
``` 

What is more surprising is that `ranger` works fine if I explicitly convert the factor variables to dummies before passing the data to `ranger`: 

```{R}
library(wakefield)
library(ranger)

# using wakefield
sample_size = 1e4
df_foo = r_data_frame(
  n = sample_size,
  ID = id,
  y = dummy,
  r_series(wakefield::r_sample_factor, j = 10, n = sample_size, name = "Factor")
)

# create the formula object
formula_ranger = as.formula(paste0("as.factor(y) ~", paste0("Factor_", 1:10, collapse = "+")))

# run ranger
# HANGS!
ranger_foo = ranger(formula = formula_ranger, 
                    data = df_foo, 
                    num.trees = 100, 
                    mtry = 4,
                    write.forest = TRUE, 
                    respect.unordered.factors = TRUE, 
                    verbose = TRUE)

# create the dummies by hand
mm_foo = cbind.data.frame(y = df_foo$y, model.matrix(object = formula_ranger, data = df_foo))

# run ranger
ranger_foo = ranger(formula = NULL, 
                    data = mm_foo,
                    dependent.variable.name = "y",
                    num.trees = 100, 
                    mtry = 4,
                    write.forest = TRUE, 
                    respect.unordered.factors = TRUE,
                    verbose = TRUE, 
                    seed = 1234,
                    classification = TRUE)
```

**Comment by mnwright** [comment] 2016-02-08 12:49
It doesn't hang, it's just computing for ages (the unordered factor mode is not optimised and very slow for many factor levels). However, if you reduce the sample size, another error occurs because of the as.factor() in the formula. This bug is fixed now. 

As suggested, characters are now considered as unordered if respect.unordered.factors = TRUE.

**Comment by tchakravarty** [comment] 2016-02-08 15:01
Martin,

So just to confirm -- it is always better to pre-compute the dummy variable
encoding for factor variables and pass the `model.matrix` as above? Would
the two models always be equivalent?

I will try to set up a more reasonably sized example to test this, but I am
not sure how I would handle the randomness in the two cases.

T



On Mon, Feb 8, 2016 at 1:49 PM, Marvin N. Wright <notifications@github.com>
wrote:

> It doesn't hang, it's just computing for ages (the unordered factor mode
> is not optimised and very slow for many factor levels). However, if you
> reduce the sample size, another error occurs because of the as.factor() in
> the formula. This bug is fixed now.
>
> As suggested, characters are now considered as unordered if
> respect.unordered.factors = TRUE.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mnwright/ranger/issues/36#issuecomment-181353945>.
>



-- 
Tirthankar Chakravarty
tchakravarty@ucsd.edu
tirthankar.chakravarty@gmail.com

**Comment by mnwright** [comment] 2016-03-02 08:52
Sorry for the delay! The models are not equivalent. I guess the performance of the models depends on the data. It would be interesting to compare the performance of the 3 options (with tuned mtry value).

**Comment by tchakravarty** [comment] 2016-03-11 11:31
@mnwright Any suggestions on the simulation setups to use to test this difference?

**Comment by mnwright** [comment] 2016-03-14 09:05
I would start with some multinomial distributed features with, say, 4, 8, 12 and 16 categories. The effects could be simulated by a tree. It's important to tune the mtry value because the dummy approach will increase the number of features. For evaluation I would go for training and testing data instead of the OOB error. 

Maybe there is even a real dataset you could use?

**Comment by PhilippPro** [comment] 2016-03-31 14:35
Two more questions regarding the order: 
How do you determine the order of the character variable?

In "The elements of Statistical Learning" in chapter 9.2.4 (http://statweb.stanford.edu/~tibs/ElemStatLearn/) they suggest to order unordered variables in case of binary outcomes, by there appearances in outcome class 1. Similarly in the regression case (and possibly this could be also applied in the multiclass case by some similarity approach).
Is this implemented in ranger? Maybe this would be a possibility to speed up computation.

**Comment by mnwright** [comment] 2016-03-31 15:09
For unordered factors the internal coding of R is used. I think the levels are ordered alphabetically and numbered starting from 1. 

Thanks for the hint on the book. Very interesting that we can get the best split without trying all unordered splits! I will also look into the approximations for multicategory outcomes.

**Comment by mnwright** [comment] 2016-06-02 19:49
The approach described by Hastie et al. is now added and used by default. I'll close here.

**Comment by berndbischl** [comment] 2016-06-04 09:44
@mnwright 

I think you should reopen the issue here. If you want to I would offer to help in the discussion. I do think you made some progress before.

**Comment by berndbischl** [comment] 2016-06-07 21:47
here are my 2cents on this:

- ranger should IMHO really support clever and faster splitting for unordered factors. this is important, as not doing this is really too slow and stupid. and the limitation on < 20 or 40 or 60 levels, suck too.

- IMHO you already made a lot of progess in the last try

- for MSE regression and binary classification you have to resort the levels for each new tried split. @PhilippPro has linked to the details. IIRC it is provable that for this the true best split is then contained in the linear search over this order.

- this faster implementation should always be done for respect.unordered.factors = TRUE, in the cases that i have outlined

- for all other cases (multiclass or survival or whatever) i currently dont know a better way for unordered factors. but who cares? the faster impl. for the 2 cases discussed here already improve range A LOT. 

- it should be properly doced what happens. not hard. 

-  respect.unordered.factors = TRUE should IMHO always be the default

**Closed** 2023-09-25 19:19 UTC
