### ISSUE TITLE
can ranger work with sparse matrices?

### ISSUE THREAD

**Issue by randomgambit** [imbs-hl/ranger#135] opened 2016-10-28 02:11 UTC
Hello there!

Congrats for this great piece of software!

I have a quick question: can `ranger` work properly with sparse matrices (coming, for instance, from `quanteda`)?

Or I need to transform the sparse matrix into a normal one (which would crash my computer)?

Thanks!

**Comment by mnwright** [comment] 2016-10-28 06:10
No, that's currently not possible. However, several people have asked for that and I'll probably add it some time. 

Is there a standard for sparse matrices in R?

**Comment by PhilippPro** [comment] 2016-10-28 07:23
I think the "Matrix" package is very common. 

Look at this post: http://stackoverflow.com/questions/1167448/most-mature-sparse-matrix-package-for-r

**Comment by randomgambit** [comment] 2016-10-28 17:02
@mnwright I think implementing that will seriously boost your package in terms of popularity. Think about it: most of the phd I work with are turn to machine learning to understand very large datasets that would be difficult to work with with linear models. Hence, there is a huge demand for packages capables of handling these datasets, and naturally, sparse matrices.

**Comment by caprice-j** [comment] 2016-11-18 23:11
Same here. I tried to use the output of `dfm` function in `quanteda` and failed.
Converting to `matrix` class worked but since my matrix is pretty large (about 500,000 x 20,000 ), it's preferable to be sparseMatrix (99% of entries are zeros).
I'm thinking about using another library.

**Comment by randomgambit** [comment] 2017-03-22 00:56
hello there! any updates? 
thanks!

**Comment by dselivanov** [comment] 2017-03-23 03:41
+1

**Comment by mnwright** [comment] 2017-03-23 08:59
Still want to add it, I hope to find the time next month!

**Comment by randomgambit** [comment] 2017-03-25 19:32
@mnwright its about time !!!! :D yay

**Comment by Polkas** [comment] 2017-03-29 23:34
I am impressed by your work. I agree that implementing Matrix functionality boost your package but this is not a clue. ranger need only one thing mouth to mouth advertisement. I think that it is to late (to much writing) to implement Sparse Matrix. If you build your package under Armadillo it would be easier. http://arma.sourceforge.net/docs.html   Next time I want to thank you for a great job. I wait for a new stuff from you. Ps. I do not understand this pressure nowadays for sparse matrix. We have many sampling methods and algorithms for variable selection. Moreover the potential profit in an accuracy on a bigger database is valuable only for Kagglers.

**Comment by dselivanov** [comment] 2017-03-30 04:23
@Polkas question here is not on how to promote package, but about additional functionality. If you don't work with sparse data it does not mean that others also don't work. Conclusion about kaggle is  especially funny.

**Comment by Polkas** [comment] 2017-03-30 11:24
So more precisely if you need a fast solution for sparseMatrix use ML-"Kalaschnikov" i.e. XGBoost - boosted randomForest. Of course I understand this demand for a  sparse matrix functionality but frequency of the author post suggest that he is busy. I think I would be easier if author will implemented a unequal prob sampling (I do not see this option). However I understand that it will not solve all problems.

**Comment by suvigy-epam** [comment] 2017-03-30 16:17
+1

**Comment by mnwright** [comment] 2017-04-11 14:40
I've drafted a version supporting sparse matrices of type `Matrix::dgCMatrix` using `RccpEigen`. 

Currently the formula interface is not working and you'll have to use `classification = TRUE` for classification (no factors in matrices). For example: 

    library(ranger)
    library(Matrix)
    iris_sparse <- Matrix(data.matrix(iris), sparse = TRUE)
    ranger(data = iris_sparse, dependent.variable.name = "Species", classification = TRUE)

It seems to be a little slower compared to using dense matrices. The reason is probably that element-wise access is not optimal in sparse matrices. I've tried with `RcppArmadillo` before, and it was way slower. 

I've little experience with sparse matrices, so suggestions and improvements are very welcome.

**Comment by mnwright** [comment] 2017-04-26 11:09
Merged. Please reopen in case of problems/questions.

**Closed by mnwright** 2017-04-26 11:09 UTC

**Comment by randomgambit** [comment] 2017-04-26 11:10
thanks!! will try.

**Comment by esox** [comment] 2017-05-28 21:00
@mnwright  , following up on this same note. I have encountered the same issue. Please see my test code and error below.

Any chance you know how to address this? Many thanks!

P.S: I realize that the current number of columns of my matrix is pretty high - I will for sure run through an elastic net prior to feeding it to ranger in the future.
```{r}
library(ranger)
library(Matrix)

X = rsparsematrix(nrow = 3027, ncol = 16988, density = 0.5)
Y = rnorm(3027) 

mat = cBind(X,Y)
r=ranger(data = mat, dependent.variable.name = "Y", 
         classification = TRUE, num.trees = 10,
         seed = 1776)
```
<sparse>[ <logic> ] : .M.sub.i.logical() maybe inefficient
Error in .local(x, i, j, ..., value) : 
  RHS 'value' (class list) matches 'ANY', but must match matrix class dgCMatrix

**Comment by mnwright** [comment] 2017-06-06 09:19
I've tried your example and it did work fine. Any idea how to reproduce the issue?

**Comment by PhilippPro** [comment] 2017-06-06 14:42
I got the same problem with that code. Newest ranger and newest Matrix package version. System: Debian.

**Comment by mnwright** [comment] 2017-06-08 12:44
Did you install the Github version? This feature is not on CRAN yet.

**Comment by PhilippPro** [comment] 2017-06-08 13:09
Ah ok, yes this solved the problem, I was not aware of that.
