### ISSUE TITLE
Devtools installation failed

### ISSUE THREAD

**Issue by traffinot** [imbs-hl/ranger#145] opened 2016-11-22 11:22 UTC
Thanks for the terrific job. 
I would like to use extratrees so I try to install the latest version but I do not manage to do it. 
May you know why ? 
![install issue](https://cloud.githubusercontent.com/assets/22389184/20522018/587190f4-b0ae-11e6-9463-4ab1f5542156.png)

**Comment by mnwright** [comment] 2016-11-22 11:54
Do you have the newest version of the [RTools](https://cran.r-project.org/bin/windows/Rtools/) installed?

**Comment by traffinot** [comment] 2016-11-22 12:57
Hello, 
I reinstall the latest version of Rtools, but I still have the same issue: I do not manage to install the latest version. 

PS : I found this paper on random forest, which is worth a read. 
Best regards

 

   

 Le Mardi 22 novembre 2016 12h55, Marvin N. Wright <notifications@github.com> a écrit :
 

 Do you have the newest version of the RTools installed?—

**Comment by mnwright** [comment] 2016-11-30 09:22
I can confirm this. The problem seems to be with symbolic links: 

The files in `ranger-r-package/ranger/src/` are symlinks to `source/src/**/*`. The windows build system seems to have problems with that. 

Any idea how to solve this?

**Comment by Eric2333** [comment] 2017-01-30 19:05
I think I am getting similar problem in Linux:
![screen shot 2017-01-30 at 11 03 36 am](https://cloud.githubusercontent.com/assets/20192845/22437194/f4d539ce-e6db-11e6-934d-67d352837e3a.png)

**Comment by bquistorff** [comment] 2017-02-03 21:34
I think I found a work-around. 

If you use `devtools::install_github()` it will download a zip, but when unzipping it converts symlinks into text files with just the target paths. If an alternative "correct" command-line unzip is available it could probably be used, but I don't know of any (`utils::unzip`, windows explorer, and 7zip all fail at this). 

It is possible to clone git repos that have symlinks with Git for Windows but not with the default method used by `devtools::install_git()` (`libgit2`). So the work around is to use  `devtools::install_git()` but swap in a well cloned directory for the badly cloned one after it's downloaded but before it's used (there may be other ways).

1. Clone the repo using Git for Windows. You will need to be in administrator mode and have set the global property `core.symlinks=true`. See [here](https://github.com/git-for-windows/git/wiki/Symbolic-Links) for more info.

2. Start R and run
```
debugonce(devtools::install_git)
devtools::install_git("git://github.com/imbs-hl/ranger.git", subdir = "ranger-r-package/ranger")
```
3. We want to stop after `remote_download()`. So "step info" the following functions: `install_remotes` -> `invisible` -> `.Internal`. Then "step over" the lines through `bundle <- remote_download(remote, quiet = quiet)`.
4. In a file manager, go to the folder specified by the `bundle` variable (it'll be something like `C:\Users\USERNAME\AppData\Local\Temp\RtmpXXXXXX\fileXXXX`) and replace that badly cloned repo with the good one.
5. Back in R, continue execution to finish the install.

That worked for me. FYI, I've posted a [bug report](https://github.com/libgit2/libgit2/issues/4107) at libgit2 so hopefully it can be done easily with `devtools::install_git()`.

**Comment by mnwright** [comment] 2017-02-09 08:16
Thanks @bquistorff for the workaround. Unfortunately, I don't think a solution is possible in the current structure, Windows just doesn't support symbolic links without hassles. 

It might work to restructure the whole project: Change the structure as in a standard R package, i.e., move everything from `ranger-r-package/ranger` to the root. Everything not related to the R package would have to be added to `.Rbuildignore`. If this is working, the devtools installation should work without the `subdir` option and it should even work on Windows. On the other hand, there wouldn't be a clear distinction between the C++ core and the R package anymore... 

Any other ideas?

**Comment by mnwright** [comment] 2017-03-20 15:39
I've created a fork implementing my suggestion: https://github.com/mnwright/ranger.
Try `devtools::install_github("mnwright/ranger")` on Windows. 
It's also nice to get rid of the `subdir` in the `install_github()` call.

Any objections?

**Comment by mnwright** [comment] 2017-04-10 11:34
Merged. New command to install from GitHub is 
`devtools::install_github("imbs-hl/ranger")`.

**Closed** 2017-05-15 13:28 UTC
